### ISSUE TITLE
Proposal Feedback

### ISSUE THREAD

**Issue by andywynkoop** [mwojick/treatpal#1]
Hey Matt,
Your proposal looks pretty good to me and I think you're ready to get started. Here are a few suggestions for some changes you might want to make. We can have a meeting at some point tomorrow and talk through any questions you have about features/details/etc.

# MVPs
-  [x] Remember to add bullet points for each MVP for adequate styling, smooth bug-free navigation, and seed data
- [x] For treat viewing, maybe add some details about what treats users will be able to see by default/ before they enter any details or search. Can users set their location?
- [x] Consider adding some details about how your search functionality will work. Will users be able to enter queries for a favorite shop or treat into the same search bar? If so, you should think about how you can best implement this on the backend and what those routes will look like.
- [x] Maybe add more details about how reservations will work.

# Database Schema
- [x] Add `backticks` to column names
- [x] Think about which tables might need image urls. Definitely treats, possibly also shops and user
# Routes 
 - [x] Don't forget session routes
- [x] Decide what type of search routes you'll need
- [x] Backend routes should be `snake_cased`
# State shape
- [x] Favorites
# Component Heirarchy
- [x] Will NavBar need to be a container?
- [x] Looking at your wireframe, it looks like your favorite button will be on a treat item. When you save a treat as a favorite, will the user be favoriting that treat or just the shop it came from?

Great Job!
Andy

**Comment by mwojick** [comment]
>  Looking at your wireframe, it looks like your favorite button will be on a treat item. When you save a treat as a favorite, will the user be favoriting that treat or just the shop it came from?

Yeah it's a bit confusing but on MealPal you actually favorite the restaurant. Maybe I should make it more clear.
