### ISSUE TITLE
PA Review: Search by treat / favorites / map

### ISSUE THREAD

**Issue by mwojick** [mwojick/treatpal#4]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by andywynkoop** [comment]
Everything looks great! Just a few suggestions:

- [ ] If you capitalize anything in the search query it won't return any results.
- [ ]  If the query doesn't return any results, the server shouldn't be throwing a 404 error. It should still be a successful response status even though it's empty.
- [ ] Hovering over a search result item should show some visual indication on the map (meal pal changes the marker color)
- [ ] Map should reflect only the current search results
- [ ] When the favorites button is clicked, it should also filter what the map displays

**Comment by mwojick** [comment]
> If you capitalize anything in the search query it won't return any results.

I had a syntax issue in my controller.

> If the query doesn't return any results, the server shouldn't be throwing a 404 error. It should still be a successful response status even though it's empty.

I had to change the server response to 200 but then because it wouldn't hit my error response after the promise, I had to check in the .then success statement if the payload was an array or not (since I know it will only be an array if it's an error message). If it is, I dispatch the error action creator.
