### ISSUE TITLE
PA Review: Reserve treats

### ISSUE THREAD

**Issue by mwojick** [mwojick/treatpal#5]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by andywynkoop** [comment]
- [ ] When I make a reservation, I should see some visual confirmation that it was successful. Maybe have the text change from 'reserve now' to 'reserved!'
- [ ] Similarly, when I try to make another reservation while I have an existing one, I should be warned about cancelling
- [ ] The purple stars for favorites are a little too large, they should probably be the same size as the header text

**Comment by mwojick** [comment]
> When I make a reservation, I should see some visual confirmation that it was successful. Maybe have the text change from 'reserve now' to 'reserved!'

I made it so that when you click the reserve button, it scrolls you to the top.

> Similarly, when I try to make another reservation while I have an existing one, I should be warned about cancelling

I'm just allowing users to update their reservation by choosing a different one, so I don't think I have to worry about canceling it.
