### ISSUE TITLE
PA Review: Account profile / order history

### ISSUE THREAD

**Issue by mwojick** [mwojick/treatpal#6]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by andywynkoop** [comment]
- [ ] Bob Ross is a great demo user
Everything looks awesome nice work
